# general settings
name: BSRN_x4_C64B8_L1_1000k
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 1

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
#    dataroot_gt: /mnt/yxsun/Project/Data/datasets/DIV2K/DIV2K_train_HR_sub
#    dataroot_lq: /mnt/yxsun/Project/Data/datasets/DIV2K/DIV2K_train_LR_bicubic/X4_sub
#    (for lmdb)
    dataroot_gt: E:\SISR\SRCNN\Flickr2K\Flickr2K_train_HR.lmdb
    dataroot_lq: E:\SISR\SRCNN\Flickr2K\Flickr2K_train_LR_bicubic\X4.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb
      # (for lmdb)
      # type: lmdb

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: True
    num_worker_per_gpu: 12
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: E:\SISR\datasets\Input\Set14\GTmod4
    dataroot_lq: E:\SISR\datasets\Input\Set14\LRbicx4
    io_backend:
      type: disk

# network structures
network_g:
  #type: RFDN
  type: BSRN
  num_in_ch: 3
  num_feat: 64
  num_block: 8
  num_out_ch: 3
  upscale: 4
  conv: BSConvU

# path
path:
  pretrain_network_g: ~
  strict_load_g: True
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: MultiStepLR
    milestones: [ 250000, 400000, 450000, 475000 ]
    gamma: 0.5

  # total_iter: 500000
  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e3
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: True

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
